package org.jellyfin.mobile.feature.music

import org.jellyfin.sdk.model.UUID

enum class MusicSongAction {
    PLAY,
    START_MIX,
    PLAY_NEXT,
    ADD_TO_QUEUE,
    ADD_TO_PLAYLIST,
    DOWNLOAD,
    GO_TO_ARTIST,
    NOT_INTERESTED,
    TOGGLE_FAVORITE,
}

data class MusicSongActionRequest(
    val action: MusicSongAction,
    val itemId: UUID,
    val source: String,
) {
    companion object {
        fun forItem(action: MusicSongAction, item: MusicItem, source: String): MusicSongActionRequest =
            MusicSongActionRequest(action = action, itemId = item.id, source = source)
    }
}

sealed interface MusicSongActionResult {
    val message: String?

    data class PlaybackStarted(val item: MusicItem) : MusicSongActionResult {
        override val message: String? = null
    }

    data class MixStarted(val seed: MusicItem, val queue: List<MusicItem>, val source: String) : MusicSongActionResult {
        override val message: String = "Starting mix from ${seed.title}."
    }

    data class QueueUpdated(override val message: String) : MusicSongActionResult

    data class PlaylistUpdated(override val message: String) : MusicSongActionResult

    data class FavoriteUpdated(val item: MusicItem, override val message: String) : MusicSongActionResult

    data class NotInterestedUpdated(
        val item: MusicItem,
        val isNotInterested: Boolean,
        override val message: String,
    ) : MusicSongActionResult

    data class ArtistRequested(val item: MusicItem) : MusicSongActionResult {
        override val message: String? = null
    }

    data class Unavailable(override val message: String) : MusicSongActionResult
}

class MusicSongActionHandler(
    private val repository: MusicRepository,
    private val playbackController: MusicPlaybackController,
) {
    suspend fun execute(
        request: MusicSongActionRequest,
        item: MusicItem,
        queue: List<MusicItem>,
    ): MusicSongActionResult {
        require(request.itemId == item.id) {
            "Song action ${request.action} targeted ${request.itemId} but received ${item.id}."
        }

        return when (request.action) {
            MusicSongAction.PLAY -> {
                val playbackQueue = queue.playableQueueFor(item)
                playbackController.play(item, playbackQueue)
                MusicSongActionResult.PlaybackStarted(item)
            }

            MusicSongAction.START_MIX -> {
                val mixQueue = repository.loadAutoGeneratedQueue(seed = item, limit = MIX_TRACK_LIMIT)
                val playbackQueue = mixQueue.playableQueueFor(item)
                playbackController.play(item = item, queue = playbackQueue)
                MusicSongActionResult.MixStarted(seed = item, queue = playbackQueue, source = request.source)
            }

            MusicSongAction.PLAY_NEXT -> {
                val result = playbackController.playNext(item)
                MusicSongActionResult.QueueUpdated(result.message)
            }

            MusicSongAction.ADD_TO_QUEUE -> {
                val result = playbackController.addToQueue(item)
                MusicSongActionResult.QueueUpdated(result.message)
            }

            MusicSongAction.ADD_TO_PLAYLIST -> {
                MusicSongActionResult.PlaylistUpdated(
                    repository.addToAutoPlaylist(item = item, source = request.source),
                )
            }

            MusicSongAction.TOGGLE_FAVORITE -> {
                val updatedItem = repository.setFavorite(item = item, favorite = !item.isFavorite)
                playbackController.updateItem(updatedItem)
                MusicSongActionResult.FavoriteUpdated(
                    item = updatedItem,
                    message = if (updatedItem.isFavorite) "Added to liked songs." else "Removed from liked songs.",
                )
            }

            MusicSongAction.NOT_INTERESTED -> {
                val isNotInterested = repository.toggleNotInterested(item)
                MusicSongActionResult.NotInterestedUpdated(
                    item = item,
                    isNotInterested = isNotInterested,
                    message = if (isNotInterested) {
                        "Marked ${item.title} as not interested."
                    } else {
                        "Removed ${item.title} from not interested."
                    },
                )
            }

            MusicSongAction.DOWNLOAD -> MusicSongActionResult.Unavailable("Downloads are not ready for Music yet.")

            MusicSongAction.GO_TO_ARTIST -> MusicSongActionResult.ArtistRequested(item)
        }
    }

    private fun List<MusicItem>.playableQueueFor(item: MusicItem): List<MusicItem> =
        filter(MusicItem::isPlayable)
            .distinctBy(MusicItem::id)
            .ifEmpty { listOf(item).filter(MusicItem::isPlayable) }
            .ensureContains(item)

    private fun List<MusicItem>.ensureContains(item: MusicItem): List<MusicItem> = when {
        any { queuedItem -> queuedItem.id == item.id } -> this
        item.isPlayable -> listOf(item) + this
        else -> this
    }

    private companion object {
        const val MIX_TRACK_LIMIT = 50
    }
}

data class MusicQueueUpdateResult(
    val queue: List<MusicItem>,
    val currentIndex: Int,
    val message: String,
    val shouldStartPlayback: Boolean = false,
)

internal object MusicQueueActions {
    fun playNext(queue: List<MusicItem>, currentIndex: Int, item: MusicItem): MusicQueueUpdateResult {
        if (!item.isPlayable) {
            return MusicQueueUpdateResult(queue, currentIndex, "This item is not playable.")
        }

        val currentItem = queue.getOrNull(currentIndex)
        if (queue.isEmpty() || currentItem == null) {
            return MusicQueueUpdateResult(
                queue = listOf(item),
                currentIndex = 0,
                message = "Playing ${item.title}.",
                shouldStartPlayback = true,
            )
        }

        if (currentItem.id == item.id) {
            return MusicQueueUpdateResult(queue, currentIndex, "${item.title} is already playing next.")
        }

        val queueWithoutItem = queue.filterNot { queuedItem -> queuedItem.id == item.id }
        val adjustedCurrentIndex = queueWithoutItem.indexOfFirst { queuedItem -> queuedItem.id == currentItem.id }
            .takeIf { index -> index >= 0 }
            ?: currentIndex.coerceIn(0, queueWithoutItem.lastIndex.coerceAtLeast(0))
        val insertIndex = (adjustedCurrentIndex + 1).coerceIn(0, queueWithoutItem.size)
        val updatedQueue = queueWithoutItem.toMutableList().apply {
            add(insertIndex, item)
        }
        val updatedCurrentIndex = updatedQueue.indexOfFirst { queuedItem -> queuedItem.id == currentItem.id }
            .coerceAtLeast(0)

        return MusicQueueUpdateResult(
            queue = updatedQueue,
            currentIndex = updatedCurrentIndex,
            message = "Playing ${item.title} next.",
        )
    }

    fun addToQueue(queue: List<MusicItem>, currentIndex: Int, item: MusicItem): MusicQueueUpdateResult {
        if (!item.isPlayable) {
            return MusicQueueUpdateResult(queue, currentIndex, "This item is not playable.")
        }

        if (queue.isEmpty()) {
            return MusicQueueUpdateResult(
                queue = listOf(item),
                currentIndex = 0,
                message = "Added ${item.title} to the queue.",
            )
        }

        if (queue.any { queuedItem -> queuedItem.id == item.id }) {
            return MusicQueueUpdateResult(queue, currentIndex.coerceIn(0, queue.lastIndex), "${item.title} is already in queue.")
        }

        return MusicQueueUpdateResult(
            queue = queue + item,
            currentIndex = currentIndex.coerceIn(0, queue.lastIndex),
            message = "Added ${item.title} to the queue.",
        )
    }
}

internal object MusicSmartQueueBuilder {
    fun initialQueue(selected: MusicItem, candidates: List<MusicItem>): List<MusicItem> =
        (listOf(selected) + candidates)
            .filter(MusicItem::isPlayable)
            .distinctBy(MusicItem::id)
}

internal object MusicGeneratedMixBuilder {
    fun build(
        seed: MusicItem,
        candidates: List<MusicItem>,
        notInterestedIds: Set<UUID>,
        maxTracks: Int,
    ): List<MusicItem> {
        val safeLimit = maxTracks.coerceIn(MIN_TRACKS, MAX_TRACKS)
        return (listOf(seed) + candidates)
            .asSequence()
            .filter(MusicItem::isPlayable)
            .filter { item -> item.id == seed.id || item.id !in notInterestedIds }
            .distinctBy(MusicItem::id)
            .take(safeLimit)
            .toList()
    }

    private const val MIN_TRACKS = 25
    private const val MAX_TRACKS = 50
}

internal object MusicArtistNavigation {
    fun hasArtistTarget(item: MusicItem): Boolean =
        item.artistIds.isNotEmpty() || !item.artist.isNullOrBlank()
}
