param(
    [switch] $Quiet
)

$ErrorActionPreference = "Stop"

$GeneratedMarker = "Generated by tools/books/generate-books-test-assets.ps1"

function Get-RepoRoot {
    return (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
}

function Ensure-Directory {
    param([string] $Path)
    New-Item -ItemType Directory -Force -Path $Path | Out-Null
}

function Write-GeneratedText {
    param(
        [string] $Path,
        [string] $Content
    )

    Ensure-Directory -Path (Split-Path -Parent $Path)
    if (Test-Path $Path) {
        $existing = Get-Content -Path $Path -Raw -ErrorAction SilentlyContinue
        if ($existing -and -not $existing.Contains($GeneratedMarker)) {
            throw "Refusing to overwrite non-generated file: $Path"
        }
    }

    Set-Content -Path $Path -Value $Content -Encoding UTF8
}

function Reset-GeneratedBinary {
    param([string] $Path)
    Ensure-Directory -Path (Split-Path -Parent $Path)
    if (Test-Path $Path) {
        Remove-Item -LiteralPath $Path -Force
    }
}

function Add-ZipTextEntry {
    param(
        [System.IO.Compression.ZipArchive] $Zip,
        [string] $Path,
        [string] $Content,
        [System.IO.Compression.CompressionLevel] $CompressionLevel = [System.IO.Compression.CompressionLevel]::Optimal
    )

    $entry = $Zip.CreateEntry($Path, $CompressionLevel)
    $stream = $entry.Open()
    try {
        $encoding = New-Object System.Text.UTF8Encoding($false)
        $writer = New-Object System.IO.StreamWriter($stream, $encoding)
        try {
            $writer.Write($Content)
        } finally {
            $writer.Dispose()
        }
    } finally {
        $stream.Dispose()
    }
}

function Escape-PdfText {
    param([string] $Value)
    return $Value.Replace("\", "\\").Replace("(", "\(").Replace(")", "\)")
}

function New-GeneratedPdf {
    param(
        [string] $Path,
        [string] $Title,
        [int] $PageCount,
        [switch] $ScannedLike
    )

    Reset-GeneratedBinary -Path $Path

    $encoding = [System.Text.Encoding]::ASCII
    $objects = New-Object System.Collections.Generic.List[object]

    function Add-PdfObject {
        param(
            [int] $Number,
            [string] $Body
        )
        $objects.Add([pscustomobject]@{ Number = $Number; Body = $Body }) | Out-Null
    }

    $pageObjectNumbers = @()
    for ($page = 1; $page -le $PageCount; $page++) {
        $pageObjectNumber = 4 + (($page - 1) * 2)
        $contentObjectNumber = $pageObjectNumber + 1
        $pageObjectNumbers += $pageObjectNumber

        $lines = New-Object System.Collections.Generic.List[string]
        $lines.Add("0 g") | Out-Null
        $lines.Add("BT") | Out-Null
        $lines.Add("/F1 18 Tf") | Out-Null
        $lines.Add("72 748 Td ($(Escape-PdfText -Value $Title)) Tj") | Out-Null
        $lines.Add("0 -28 Td (Page $page of $PageCount) Tj") | Out-Null
        $lines.Add("/F1 11 Tf") | Out-Null
        $lines.Add("0 -34 Td (This file contains generated validation text only. It is not copyrighted book content.) Tj") | Out-Null
        $lines.Add("ET") | Out-Null

        if ($ScannedLike) {
            for ($row = 0; $row -lt 22; $row++) {
                $gray = if ($row % 2 -eq 0) { "0.86" } else { "0.78" }
                $y = 660 - ($row * 24)
                $width = 420 + (($row % 5) * 18)
                $lines.Add("$gray g") | Out-Null
                $lines.Add("72 $y $width 10 re f") | Out-Null
            }
            $lines.Add("0 g") | Out-Null
            $lines.Add("BT /F1 12 Tf 92 92 Td (Simulated scanned page with generated gray bands.) Tj ET") | Out-Null
        } else {
            for ($paragraph = 1; $paragraph -le 8; $paragraph++) {
                $y = 610 - (($paragraph - 1) * 48)
                $lines.Add("BT /F1 12 Tf 72 $y Td (Generated paragraph $paragraph for reader navigation, caching, and progress validation.) Tj ET") | Out-Null
            }
        }

        $content = ($lines -join "`n")
        $contentLength = $encoding.GetByteCount($content)
        Add-PdfObject -Number $contentObjectNumber -Body "<< /Length $contentLength >>`nstream`n$content`nendstream"
        Add-PdfObject -Number $pageObjectNumber -Body "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents $contentObjectNumber 0 R >>"
    }

    Add-PdfObject -Number 1 -Body "<< /Type /Catalog /Pages 2 0 R >>"
    Add-PdfObject -Number 2 -Body "<< /Type /Pages /Kids [$($pageObjectNumbers | ForEach-Object { "$_ 0 R" })] /Count $PageCount >>"
    Add-PdfObject -Number 3 -Body "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"

    $orderedObjects = $objects | Sort-Object Number
    $builder = New-Object System.Text.StringBuilder
    $offsets = @{}
    [void] $builder.Append("%PDF-1.4`n")
    foreach ($object in $orderedObjects) {
        $offsets[$object.Number] = $encoding.GetByteCount($builder.ToString())
        [void] $builder.Append("$($object.Number) 0 obj`n$($object.Body)`nendobj`n")
    }

    $startXref = $encoding.GetByteCount($builder.ToString())
    $maxObject = ($orderedObjects | Select-Object -ExpandProperty Number | Measure-Object -Maximum).Maximum
    [void] $builder.Append("xref`n")
    [void] $builder.Append("0 $($maxObject + 1)`n")
    [void] $builder.Append("0000000000 65535 f `n")
    for ($number = 1; $number -le $maxObject; $number++) {
        $offset = if ($offsets.ContainsKey($number)) { $offsets[$number] } else { 0 }
        [void] $builder.Append(("{0:D10} 00000 n `n" -f $offset))
    }
    [void] $builder.Append("trailer`n")
    [void] $builder.Append("<< /Size $($maxObject + 1) /Root 1 0 R >>`n")
    [void] $builder.Append("startxref`n$startXref`n%%EOF`n")

    [System.IO.File]::WriteAllText($Path, $builder.ToString(), $encoding)
}

function New-EpubChapterHtml {
    param(
        [string] $Title,
        [int] $ChapterNumber,
        [int] $ParagraphCount
    )

    $paragraphs = for ($index = 1; $index -le $ParagraphCount; $index++) {
        "<p>Generated paragraph $index in chapter $ChapterNumber. This dummy text validates native EPUB parsing, navigation, resume, and clean text rendering without using copyrighted content.</p>"
    }

    return @"
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head><title>$Title</title></head>
  <body>
    <h1>$Title</h1>
    <p><strong>Generated</strong> EPUB sample with <em>native</em> text cleanup markers.</p>
    <p><a href="#note-$ChapterNumber">1</a> Footnote-style link for validation.</p>
    <img alt="Generated placeholder image" src="images/chapter-$ChapterNumber.png" />
    <pre>line one
line two</pre>
    $($paragraphs -join "`n    ")
  </body>
</html>
"@
}

function New-GeneratedEpub {
    param(
        [string] $Path,
        [string] $Title,
        [int] $ChapterCount,
        [ValidateSet("Nav", "NcxOnly", "BrokenMetadata")] [string] $Mode,
        [int] $ParagraphsPerChapter = 4
    )

    Reset-GeneratedBinary -Path $Path
    $stream = [System.IO.File]::Open($Path, [System.IO.FileMode]::CreateNew)
    try {
        $zip = New-Object System.IO.Compression.ZipArchive($stream, [System.IO.Compression.ZipArchiveMode]::Create)
        try {
            Add-ZipTextEntry -Zip $zip -Path "mimetype" -Content "application/epub+zip" -CompressionLevel ([System.IO.Compression.CompressionLevel]::NoCompression)
            Add-ZipTextEntry -Zip $zip -Path "META-INF/container.xml" -Content @'
<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
'@

            $manifestItems = New-Object System.Collections.Generic.List[string]
            $spineItems = New-Object System.Collections.Generic.List[string]
            for ($chapter = 1; $chapter -le $ChapterCount; $chapter++) {
                $manifestItems.Add("    <item id=`"c$chapter`" href=`"chapter-$chapter.xhtml`" media-type=`"application/xhtml+xml`"/>") | Out-Null
                $spineItems.Add("    <itemref idref=`"c$chapter`"/>") | Out-Null
                Add-ZipTextEntry -Zip $zip -Path "OEBPS/chapter-$chapter.xhtml" -Content (New-EpubChapterHtml -Title "Generated Chapter $chapter" -ChapterNumber $chapter -ParagraphCount $ParagraphsPerChapter)
            }

            if ($Mode -eq "Nav" -or $Mode -eq "BrokenMetadata") {
                $manifestItems.Insert(0, '    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>')
                $navItems = for ($chapter = 1; $chapter -le $ChapterCount; $chapter++) {
                    "      <li><a href=`"chapter-$chapter.xhtml`">Generated Chapter $chapter</a></li>"
                }
                Add-ZipTextEntry -Zip $zip -Path "OEBPS/nav.xhtml" -Content @"
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
  <body>
    <nav epub:type="toc">
      <ol>
$($navItems -join "`n")
      </ol>
    </nav>
  </body>
</html>
"@
            }

            if ($Mode -eq "NcxOnly") {
                $manifestItems.Insert(0, '    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>')
                $ncxPoints = for ($chapter = 1; $chapter -le $ChapterCount; $chapter++) {
                    @"
      <navPoint id="navPoint-$chapter" playOrder="$chapter">
        <navLabel><text>NCX Chapter $chapter</text></navLabel>
        <content src="chapter-$chapter.xhtml"/>
      </navPoint>
"@
                }
                Add-ZipTextEntry -Zip $zip -Path "OEBPS/toc.ncx" -Content @"
<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head><meta name="dtb:uid" content="ptv-generated-ncx"/></head>
  <docTitle><text>$Title</text></docTitle>
  <navMap>
$($ncxPoints -join "`n")
  </navMap>
</ncx>
"@
            }

            $metadata = if ($Mode -eq "BrokenMetadata") {
                "  <metadata xmlns:dc=`"http://purl.org/dc/elements/1.1/`">`n  </metadata>"
            } else {
                "  <metadata xmlns:dc=`"http://purl.org/dc/elements/1.1/`">`n    <dc:title>$Title</dc:title>`n    <dc:creator>PiggieTV Generated Test Asset</dc:creator>`n  </metadata>"
            }
            $spineToc = if ($Mode -eq "NcxOnly") { ' toc="ncx"' } else { "" }
            Add-ZipTextEntry -Zip $zip -Path "OEBPS/content.opf" -Content @"
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="bookid">
$metadata
  <manifest>
$($manifestItems -join "`n")
  </manifest>
  <spine$spineToc>
$($spineItems -join "`n")
  </spine>
</package>
"@
        } finally {
            $zip.Dispose()
        }
    } finally {
        $stream.Dispose()
    }
}

function New-GeneratedPngBytes {
    param(
        [int] $PageNumber,
        [int] $PageCount,
        [string] $Title,
        [switch] $Rtl
    )

    Add-Type -AssemblyName System.Drawing
    $bitmap = New-Object System.Drawing.Bitmap 900, 1300
    $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
    try {
        $graphics.Clear([System.Drawing.Color]::FromArgb(250, 250, 246))
        $pen = New-Object System.Drawing.Pen ([System.Drawing.Color]::FromArgb(40, 70, 90)), 4
        $brush = New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::FromArgb(30, 35, 40))
        $accent = New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::FromArgb(86, 148, 190))
        $fontTitle = New-Object System.Drawing.Font "Arial", 34, ([System.Drawing.FontStyle]::Bold)
        $fontBody = New-Object System.Drawing.Font "Arial", 22, ([System.Drawing.FontStyle]::Regular)
        $fontHuge = New-Object System.Drawing.Font "Arial", 82, ([System.Drawing.FontStyle]::Bold)
        try {
            $graphics.DrawRectangle($pen, 34, 34, 832, 1232)
            $graphics.DrawString($Title, $fontTitle, $brush, 72, 86)
            $graphics.DrawString("Generated validation page", $fontBody, $brush, 72, 150)
            $graphics.DrawString("$PageNumber / $PageCount", $fontHuge, $accent, 290, 520)
            $direction = if ($Rtl) { "RTL manga-style: read right to left" } else { "LTR generated comic page" }
            $graphics.DrawString($direction, $fontBody, $brush, 72, 740)
            for ($row = 0; $row -lt 8; $row++) {
                $y = 820 + ($row * 42)
                $graphics.DrawRectangle($pen, 72, $y, 680 - (($row % 3) * 90), 18)
            }
            if ($Rtl) {
                $graphics.DrawString("<-- previous visual flow", $fontBody, $accent, 500, 1130)
                $graphics.DrawString("next visual flow -->", $fontBody, $accent, 72, 1170)
            }
        } finally {
            $fontTitle.Dispose()
            $fontBody.Dispose()
            $fontHuge.Dispose()
            $brush.Dispose()
            $accent.Dispose()
            $pen.Dispose()
        }

        $memory = New-Object System.IO.MemoryStream
        $bitmap.Save($memory, [System.Drawing.Imaging.ImageFormat]::Png)
        return $memory.ToArray()
    } finally {
        $graphics.Dispose()
        $bitmap.Dispose()
    }
}

function New-GeneratedCbz {
    param(
        [string] $Path,
        [string] $Title,
        [int] $PageCount,
        [switch] $Rtl
    )

    Reset-GeneratedBinary -Path $Path
    $stream = [System.IO.File]::Open($Path, [System.IO.FileMode]::CreateNew)
    try {
        $zip = New-Object System.IO.Compression.ZipArchive($stream, [System.IO.Compression.ZipArchiveMode]::Create)
        try {
            for ($page = 1; $page -le $PageCount; $page++) {
                $entryName = "page-{0:D3}.png" -f $page
                $entry = $zip.CreateEntry($entryName, [System.IO.Compression.CompressionLevel]::Optimal)
                $entryStream = $entry.Open()
                try {
                    $bytes = New-GeneratedPngBytes -PageNumber $page -PageCount $PageCount -Title $Title -Rtl:$Rtl
                    $entryStream.Write($bytes, 0, $bytes.Length)
                } finally {
                    $entryStream.Dispose()
                }
            }
        } finally {
            $zip.Dispose()
        }
    } finally {
        $stream.Dispose()
    }
}

function New-GeneratedTextBook {
    param(
        [string] $Path,
        [string] $Title,
        [int] $ParagraphCount
    )

    $paragraphs = for ($index = 1; $index -le $ParagraphCount; $index++) {
        "Paragraph $index. This generated PiggieTV Books validation text exercises native TXT pagination, resume, settings persistence, and long-document scrolling."
    }
    Write-GeneratedText -Path $Path -Content @"
$GeneratedMarker

$Title

$($paragraphs -join "`n`n")
"@
}

$repoRoot = Get-RepoRoot
$booksRoot = Join-Path $repoRoot "test-assets\books"
$epubDir = Join-Path $booksRoot "epub"
$pdfDir = Join-Path $booksRoot "pdf"
$cbzDir = Join-Path $booksRoot "cbz"
$txtDir = Join-Path $booksRoot "txt"
$unsupportedDir = Join-Path $booksRoot "unsupported"

Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

foreach ($directory in @($booksRoot, $epubDir, $pdfDir, $cbzDir, $txtDir, $unsupportedDir)) {
    Ensure-Directory -Path $directory
}

$readmeContent = @(
    $GeneratedMarker,
    "",
    "# Native PTV Books Generated Test Assets",
    "",
    "These files are generated dummy validation assets for PiggieTV Books runtime testing.",
    "",
    "Do not place copyrighted books, comics, manga, or commercial samples in this directory. Use public-domain, permissively licensed, or self-created files only.",
    "",
    "Regenerate the sample set with:",
    "",
    '```powershell',
    ".\tools\books\generate-books-test-assets.ps1",
    '```'
) -join "`n"
Write-GeneratedText -Path (Join-Path $booksRoot "README.md") -Content $readmeContent

$outputs = New-Object System.Collections.Generic.List[string]

New-GeneratedEpub -Path (Join-Path $epubDir "small-nav.epub") -Title "PTV Generated Small EPUB Nav" -ChapterCount 3 -Mode "Nav" -ParagraphsPerChapter 3
$outputs.Add((Join-Path $epubDir "small-nav.epub")) | Out-Null
New-GeneratedEpub -Path (Join-Path $epubDir "ncx-only.epub") -Title "PTV Generated NCX EPUB" -ChapterCount 4 -Mode "NcxOnly" -ParagraphsPerChapter 3
$outputs.Add((Join-Path $epubDir "ncx-only.epub")) | Out-Null
New-GeneratedEpub -Path (Join-Path $epubDir "large-generated.epub") -Title "PTV Generated Large EPUB" -ChapterCount 80 -Mode "Nav" -ParagraphsPerChapter 12
$outputs.Add((Join-Path $epubDir "large-generated.epub")) | Out-Null
New-GeneratedEpub -Path (Join-Path $epubDir "broken-metadata.epub") -Title "PTV Generated Broken Metadata EPUB" -ChapterCount 2 -Mode "BrokenMetadata" -ParagraphsPerChapter 2
$outputs.Add((Join-Path $epubDir "broken-metadata.epub")) | Out-Null

New-GeneratedPdf -Path (Join-Path $pdfDir "short-under-50-pages.pdf") -Title "PTV Generated Short PDF" -PageCount 12
$outputs.Add((Join-Path $pdfDir "short-under-50-pages.pdf")) | Out-Null
New-GeneratedPdf -Path (Join-Path $pdfDir "long-320-pages.pdf") -Title "PTV Generated 320 Page PDF" -PageCount 320
$outputs.Add((Join-Path $pdfDir "long-320-pages.pdf")) | Out-Null
New-GeneratedPdf -Path (Join-Path $pdfDir "simulated-scanned.pdf") -Title "PTV Generated Simulated Scanned PDF" -PageCount 80 -ScannedLike
$outputs.Add((Join-Path $pdfDir "simulated-scanned.pdf")) | Out-Null

New-GeneratedCbz -Path (Join-Path $cbzDir "small-generated.cbz") -Title "PTV Small CBZ" -PageCount 6
$outputs.Add((Join-Path $cbzDir "small-generated.cbz")) | Out-Null
New-GeneratedCbz -Path (Join-Path $cbzDir "large-generated.cbz") -Title "PTV Large CBZ" -PageCount 80
$outputs.Add((Join-Path $cbzDir "large-generated.cbz")) | Out-Null
New-GeneratedCbz -Path (Join-Path $cbzDir "rtl-manga-generated.cbz") -Title "PTV RTL Manga CBZ" -PageCount 16 -Rtl
$outputs.Add((Join-Path $cbzDir "rtl-manga-generated.cbz")) | Out-Null

New-GeneratedTextBook -Path (Join-Path $txtDir "short.txt") -Title "PTV Generated Short TXT" -ParagraphCount 10
$outputs.Add((Join-Path $txtDir "short.txt")) | Out-Null
New-GeneratedTextBook -Path (Join-Path $txtDir "long.txt") -Title "PTV Generated Long TXT" -ParagraphCount 900
$outputs.Add((Join-Path $txtDir "long.txt")) | Out-Null

$unsupportedFiles = @{
    "unsupported.cbr" = "Generated dummy CBR placeholder. This is not a real comic archive."
    "unsupported.mobi" = "Generated dummy MOBI placeholder."
    "unsupported.azw" = "Generated dummy AZW placeholder."
    "unsupported.azw3" = "Generated dummy AZW3 placeholder."
    "markdown.md" = "# Generated Markdown`n`nThis validates unsupported Markdown messaging."
    "html.html" = "<!doctype html><html><body><h1>Generated HTML</h1><p>This validates native-reader HTML limitation messaging.</p></body></html>"
    "unknown.booktest" = "Generated unknown extension placeholder."
}

foreach ($entry in $unsupportedFiles.GetEnumerator()) {
    $path = Join-Path $unsupportedDir $entry.Key
    Write-GeneratedText -Path $path -Content "$GeneratedMarker`n`n$($entry.Value)"
    $outputs.Add($path) | Out-Null
}

if (-not $Quiet) {
    Write-Host "Generated native Books validation assets:"
    foreach ($output in $outputs) {
        $item = Get-Item -LiteralPath $output
        Write-Host "  $($item.FullName) ($($item.Length) bytes)"
    }
    Write-Host ""
    Write-Host "Asset root: $booksRoot"
}
